# Generated by Django 5.2.5 on 2025-08-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw'), ('Loan Request', 'Loan Request'), ('Loan Paid', 'Loan Paid')])),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_approve_status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounts.userbankaccount')),
            ],
            options={
                'ordering': ['transaction_time'],
            },
        ),
    ]
